project:
  type: website
  output-dir: docs

website:
  title: "INvenTree"
  google-analytics: "G-PVM7NFRLL8"
  navbar:
    pinned: true
    left:
      - text: "Resources"
        icon: book
        menu: 
          - href: resources.qmd
            text: "Publications"
            # icon: folder-fill
            icon: bookmark
          - href: "https://tinyurl.com/inventreeapp"
            text: Paper Explorer
            icon: compass
            target: "_new"        
      - text: "People"
        icon: person-circle
        menu:
          - text: "Working Group"
            href: team.qmd
            # icon: list-check
            # icon: puzzle-fill
            icon: tools
          - text: "Member Directory {{< iconify bi cuia:open-in-new-tab-outline size=1.1em >}}"
            href: "https://india-inventree.github.io/members/"
            # target: "_new"
            # icon: mortarboard-fill
            icon: person-badge-fill
      - href: updates.qmd
        text: "Updates"
        icon: newspaper
      - href: join.qmd
        # text: "<span class='btn btn-primary'>Click here</span>"
        text: "Get Involved"
        # icon: person-add
        icon: sign-merge-left
    right:
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:indiainventree@gmail.com"
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/India-INvenTree
        rel: me
        target: "_new"
  page-footer:
    border: true
    left: "&#169; 2025 INvenTree"
    center: "[Code of Conduct](coc.qmd) | [Attribution](attribution.qmd) | [Privacy](privacy.qmd) | [Accessibility](accessibility.qmd)"
      # - text: "[Code of Conduct](coc.qmd)"
      #   href: coc.qmd
      #   icon: check-circle
      # - text: "   "
      # - text: "[Attribution  ](attribution.qmd)"
      #   href: attribution.qmd
      # - text: "[Privacy  ](privacy.qmd)"
      #   href: privacy.qmd
      # - text: "[Accessibility](accessibility.qmd)"
      #   href: accessibility.qmd
      #   icon: universal-access-circle
      # - text: License
      #   href: license.qmd
    right: "made with ︎♥️ & [Quarto](https://quarto.org)"


format:
  html:
    theme:
      # - cosmo
      - flatly
      - custom.scss
    css: styles.css
    toc: true

# format:
#   html:
#     theme: 
#       - html/ath.scss
#     grid: 
#       body-width: 900px
#     toc: false
#     code-link: true
#     anchor-sections: true
#     fig-cap-location: margin
#     reference-location: margin
#     footnotes-hover: true
#     highlight-style: monokai


